// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPcpr_OtBPCw9B8MhLptl_dv2HwClYbzI',
    appId: '1:603977634106:web:7a25794521e554f085c003',
    messagingSenderId: '603977634106',
    projectId: 'aula04-2fa4d',
    authDomain: 'aula04-2fa4d.firebaseapp.com',
    storageBucket: 'aula04-2fa4d.firebasestorage.app',
    measurementId: 'G-9LDRZYMTBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWSfRYQwzjtWL4rF9QhRudUaK-8U31Ho',
    appId: '1:603977634106:android:d2bde51c8e479c7e85c003',
    messagingSenderId: '603977634106',
    projectId: 'aula04-2fa4d',
    storageBucket: 'aula04-2fa4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmrhEYwrCpmWyEj5NM3QqYMny3XveYeU8',
    appId: '1:603977634106:ios:ad8686c7037252ec85c003',
    messagingSenderId: '603977634106',
    projectId: 'aula04-2fa4d',
    storageBucket: 'aula04-2fa4d.firebasestorage.app',
    iosBundleId: 'com.example.aula04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmrhEYwrCpmWyEj5NM3QqYMny3XveYeU8',
    appId: '1:603977634106:ios:ad8686c7037252ec85c003',
    messagingSenderId: '603977634106',
    projectId: 'aula04-2fa4d',
    storageBucket: 'aula04-2fa4d.firebasestorage.app',
    iosBundleId: 'com.example.aula04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPcpr_OtBPCw9B8MhLptl_dv2HwClYbzI',
    appId: '1:603977634106:web:9d1f59234d3e1aab85c003',
    messagingSenderId: '603977634106',
    projectId: 'aula04-2fa4d',
    authDomain: 'aula04-2fa4d.firebaseapp.com',
    storageBucket: 'aula04-2fa4d.firebasestorage.app',
    measurementId: 'G-XF96GZ14Z1',
  );
}
